### ISSUE TITLE
blank page for payment link

### ISSUE THREAD

**Issue by omtr** [SiimKirjanen/seatreg#98]
Hi SeatReg,

i am able to book a seat. I get a payment link that looks like this:

https://XXXXXXXXXXXXXXXX?seatreg=booking-status&registration=9ebb2ccd2d&id=98039a7c4823b2033aeb2cbf4dfbd89b0d5d5c4b

However, the page for the payment is blank, source code looks like this:

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="icon" href="" />
	<title>
		Booking check	</title>
	<style>
		.payment-forms {
			display: flex;
			align-items: center;
			flex-wrap: wrap;
			gap: 12px;
		}
		.payment-forms form {
			
		}
		.payment-instructions {
			margin: 24px 0 12px;
		}
	</style>
	<title>MyPage</title>

Wordpress is 6.2 with Astra Theme and Elementor Page Builder.
Any idea how i can get out of this issue?

**Comment by SiimKirjanen** [comment]
Can you try turning off Elementor plugins? I know that many people have had problems with it (but some have used it without no problems).  Sadly I have not managed to reproduce the issue.

**Comment by omtr** [comment]
yes, you are right. i disabled the elementor plugin and the payment link worked right away. i will pull up debugging and try to find the root cause.

**Comment by omtr** [comment]
it looks like Elementor is not the issue, but a very common for Elementor, which is called "Happy Elementor Addons". This is the output on your SeatsReg payment page when the addon is enabled:

 Fatal error: Uncaught Error: Call to undefined function Happy_Addons\Elementor\ha_is_on_demand_cache_enabled() in /OBFUSCATED_PATH/wp-content/plugins/happy-elementor-addons/classes/cache-manager.php:55 Stack trace: #0 /OBFUSCATED_PATH/wp-content/plugins/happy-elementor-addons/classes/assets-manager.php(354): Happy_Addons\Elementor\Cache_Manager::should_enqueue('186') #1 /OBFUSCATED_PATH/wp-content/plugins/happy-elementor-addons/classes/assets-manager.php(327): Happy_Addons\Elementor\Assets_Manager::enqueue('186') #2 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(308): Happy_Addons\Elementor\Assets_Manager::frontend_enqueue_exceptions(Object(Elementor\Core\Files\CSS\Post)) #3 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 /OBFUSCATED_PATH/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /OBFUSCATED_PATH/wp-content/plugins/elementor/core/files/css/base.php(264): do_action('elementor/css-f...', Object(Elementor\Core\Files\CSS\Post)) #6 /OBFUSCATED_PATH/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue() #7 /OBFUSCATED_PATH/wp-content/plugins/header-footer-elementor/inc/class-header-footer-elementor.php(400): Elementor\Core\Files\CSS\Post->enqueue() #8 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(308): Header_Footer_Elementor->enqueue_scripts('') #9 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #10 /OBFUSCATED_PATH/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #11 /OBFUSCATED_PATH/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...') #12 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('') #13 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #14 /OBFUSCATED_PATH/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #15 /OBFUSCATED_PATH/wp-includes/general-template.php(3043): do_action('wp_head') #16 /OBFUSCATED_PATH/wp-content/plugins/seatreg/php/booking_check.php(42): wp_head() #17 /OBFUSCATED_PATH/wp-content/plugins/seatreg/php/seatreg_filters.php(71): include('/www/htdocs/w01...') #18 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(308): seatreg_custom_pages('') #19 /OBFUSCATED_PATH/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #20 /OBFUSCATED_PATH/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #21 /OBFUSCATED_PATH/wp-settings.php(617): do_action('init') #22 /OBFUSCATED_PATH/wp-config.php(106): require_once('/www/htdocs/w01...') #23 /OBFUSCATED_PATH/wp-load.php(50): require_once('/www/htdocs/w01...') #24 /OBFUSCATED_PATH/wp-blog-header.php(13): require_once('/www/htdocs/w01...') #25 /OBFUSCATED_PATH/index.php(17): require('/www/htdocs/w01...') #26 {main} thrown in /OBFUSCATED_PATH/wp-content/plugins/happy-elementor-addons/classes/cache-manager.php on line 55
